# Generated by Django 3.2.16 on 2026-02-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('count_participants', models.PositiveSmallIntegerField()),
                ('year_start', models.PositiveSmallIntegerField()),
                ('year_end', models.PositiveSmallIntegerField()),
                ('adult', models.BooleanField()),
                ('vote_average', models.DecimalField(decimal_places=2, max_digits=4)),
                ('genres', models.ManyToManyField(related_name='rooms', to='movies.Genre')),
            ],
        ),
    ]
