# Generated by Django 3.2.16 on 2026-02-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20260223_1135'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'комната', 'verbose_name_plural': 'Комнаты'},
        ),
        migrations.AlterField(
            model_name='room',
            name='adult',
            field=models.BooleanField(verbose_name='18+'),
        ),
        migrations.AlterField(
            model_name='room',
            name='count_participants',
            field=models.PositiveSmallIntegerField(verbose_name='Количество участников'),
        ),
        migrations.AlterField(
            model_name='room',
            name='genres',
            field=models.ManyToManyField(related_name='rooms', to='movies.Genre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='room',
            name='vote_average',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Средний рейтинг'),
        ),
        migrations.AlterField(
            model_name='room',
            name='year_end',
            field=models.PositiveSmallIntegerField(verbose_name='Релиз до'),
        ),
        migrations.AlterField(
            model_name='room',
            name='year_start',
            field=models.PositiveSmallIntegerField(verbose_name='Релиз от'),
        ),
    ]
