# Generated by Django 3.2.16 on 2026-02-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20260223_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='adult',
            field=models.BooleanField(help_text='Контент с рейтингом 18+', verbose_name='18+'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(help_text='Название комнаты', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='room',
            name='vote_average',
            field=models.DecimalField(decimal_places=2, help_text='Средний рейтинг по TMDB', max_digits=4, verbose_name='Средний рейтинг'),
        ),
        migrations.AlterField(
            model_name='room',
            name='year_end',
            field=models.PositiveSmallIntegerField(help_text='Укажите конечный год релиза', verbose_name='Релиз до'),
        ),
        migrations.AlterField(
            model_name='room',
            name='year_start',
            field=models.PositiveSmallIntegerField(help_text='Укажите начальный год релиза. Если нужен только один год, укажите одинаковые значения в полях "Релиз от" и "Релиз до"', verbose_name='Релиз от'),
        ),
    ]
