# Generated by Django 6.0.2 on 2026-02-24 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20260223_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='room_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='adult',
            field=models.BooleanField(verbose_name='18+'),
        ),
        migrations.AlterField(
            model_name='room',
            name='count_participants',
            field=models.PositiveSmallIntegerField(help_text='от 1 до 4 участников', verbose_name='Количество участников'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(help_text='не должно превышать 100 символов', max_length=100, verbose_name='Название'),
        ),
    ]
