# Generated by Django 6.0.2 on 2026-02-24 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_participant_room_id_alter_room_adult_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'участник', 'verbose_name_plural': 'Участники'},
        ),
    ]
