# Generated by Django 6.0.2 on 2026-02-24 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_participant_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(help_text='максимальное количество символов 50', max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='room_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='rooms.room', verbose_name='ID комнаты'),
        ),
    ]
