# Generated by Django 6.0.2 on 2026-02-25 07:19

import rooms.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_participant_name_alter_participant_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='count_participants',
            field=models.PositiveSmallIntegerField(help_text='от 1 до 4 участников', validators=[rooms.validators.validate_participants_count], verbose_name='Количество участников'),
        ),
        migrations.AlterField(
            model_name='room',
            name='vote_average',
            field=models.DecimalField(decimal_places=2, help_text='Средний рейтинг по TMDB', max_digits=4, validators=[rooms.validators.validate_vote_average], verbose_name='Средний рейтинг'),
        ),
        migrations.AlterField(
            model_name='room',
            name='year_end',
            field=models.PositiveSmallIntegerField(help_text='Укажите конечный год релиза', validators=[rooms.validators.validate_year], verbose_name='Релиз до'),
        ),
        migrations.AlterField(
            model_name='room',
            name='year_start',
            field=models.PositiveSmallIntegerField(help_text='Укажите начальный год релиза. Если нужен только один год, укажите одинаковые значения в полях "Релиз от" и "Релиз до"', validators=[rooms.validators.validate_year], verbose_name='Релиз от'),
        ),
    ]
