# Generated by Django 6.0.2 on 2026-02-27 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_movie_vote_average'),
        ('rooms', '0008_alter_participant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_playing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='select_movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='Выбранный фильм'),
        ),
    ]
