# Generated by Django 6.0.2 on 2026-02-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_room_is_playing_room_select_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='is_playing',
            field=models.BooleanField(default=True),
        ),
    ]
