# Generated by Django 6.0.2 on 2026-02-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(help_text='не должно превышать 12 символов', max_length=12, verbose_name='Название'),
        ),
    ]
