# Generated by Django 3.2.16 on 2026-02-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20260223_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.RemoveField(
            model_name='genre',
            name='tmdb_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tmdb_id',
        ),
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='TMDB ID'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='adult',
            field=models.BooleanField(verbose_name='18+'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='backdrop_path',
            field=models.URLField(verbose_name='URL фона'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies', to='movies.Genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='TMDB ID'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='original_title',
            field=models.CharField(max_length=100, verbose_name='Оригинальное название'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.URLField(verbose_name='URL постера'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(verbose_name='Дата релиза'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название на русском'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vote_average',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Средний рейтинг'),
        ),
    ]
