# Generated by Django 3.2.16 on 2026-02-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20260223_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.IntegerField(help_text='Идентификатор с TMDB API (заполняется автоматически)', primary_key=True, serialize=False, verbose_name='TMDB ID'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Название жанра', max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='adult',
            field=models.BooleanField(help_text='Контент с рейтингом 18+', null=True, verbose_name='18+'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='backdrop_path',
            field=models.URLField(help_text='Открытый источник к фону по фильму', null=True, verbose_name='URL фона'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(null=True, related_name='movies', to='movies.Genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.IntegerField(help_text='Идентификатор с TMDB API (заполняется автоматически)', primary_key=True, serialize=False, verbose_name='TMDB ID'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='original_title',
            field=models.CharField(help_text='Название на языке оригинала', max_length=100, null=True, verbose_name='Оригинальное название'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.TextField(help_text='Описание на русском языке', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.URLField(help_text='Открытый источник к постеру', null=True, verbose_name='URL постера'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(help_text='Дата релиза в мире', null=True, verbose_name='Дата релиза'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(help_text='Название на русском языке', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vote_average',
            field=models.DecimalField(decimal_places=2, help_text='Средний рейтинг по TMDB', max_digits=4, null=True, verbose_name='Средний рейтинг'),
        ),
    ]
