# Generated by Django 6.0.2 on 2026-02-25 07:19

import rooms.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='vote_average',
            field=models.DecimalField(decimal_places=2, help_text='Средний рейтинг по TMDB', max_digits=4, null=True, validators=[rooms.validators.validate_vote_average], verbose_name='Средний рейтинг'),
        ),
    ]
