# Generated by Django 6.0.2 on 2026-02-26 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_alter_room_count_participants_and_more'),
        ('swipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swipe',
            name='count_likes',
        ),
        migrations.AddField(
            model_name='swipe',
            name='participant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to='rooms.participant'),
            preserve_default=False,
        ),
    ]
